sudo: true
language: java

before_install:
- openssl aes-256-cbc -K $encrypted_c71cc4aecc95_key -iv $encrypted_c71cc4aecc95_iv
  -in zmanim-travis-key.json.enc -out zmanim-travis-key.json -d

deploy:
  provider: gae
  keyfile: zmanim-travis-key.json
  project: zmanim-app
  on: master
  verbosity: debug
  config: src/main/webapp/WEB-INF/appengine-web.xml