sudo: true
language: java

before_install:
- openssl aes-256-cbc -K $encrypted_c71cc4aecc95_key -iv $encrypted_c71cc4aecc95_iv
  -in zmanim-travis-key.json.enc -out zmanim-travis-key.json -d

- gcloud auth activate-service-account --key-file zmanim-travis-key.json || die "unable to authenticate service account for gcloud"

deploy:
  provider: gae
  keyfile: zmanim-travis-key.json.enc
  project: zmanim-app
  on: master
  verbosity: debug