sudo: true
language: java

env:
  global:
    # Ensure the downloaded SDK is first on the PATH
    - PATH=${HOME}/google-cloud-sdk/bin:$PATH
    # Ensure the install happens without prompts
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
- openssl aes-256-cbc -K $encrypted_c71cc4aecc95_key -iv $encrypted_c71cc4aecc95_iv
  -in zmanim-travis-key.json.enc -out zmanim-travis-key.json -d

install:
# Make sure SDK is downloaded - cache once it's working
# NOTE: Note sure how to update the SDK if it's cached
- curl https://sdk.cloud.google.com | bash;
# List the SDK contents to ensure it's downloaded
- ls -l ${HOME}/google-cloud-sdk/bin
# Ensure the correct gcloud is being used
- which gcloud
# Print the gcloud version and make sure it's something
# Reasonably up to date compared with:
# https://cloud.google.com/sdk/downloads#versioned
- gcloud --version
- gcloud auth activate-service-account --key-file zmanim-travis-key.json || die "unable to authenticate service account for gcloud"

deploy:
  provider: gae
  keyfile: zmanim-travis-key.json.enc
  project: zmanim-app
  on: master
  verbosity: debug